name: Sample GithubActions

on:
  pull_request:
    branches:
      - main
      - develop
      - release/*
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SRC_BRANCH: ${{ github.head_ref }}
      DEST_BRANCH: ${{ github.base_ref }}
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Checkout manifest repo
      uses: ./
      with:
        name: 'application.yaml'
        srcRevision: ${{ env.SRC_BRANCH }}
        destRevision: ${{ env.DEST_BRANCH }}
