name: Release Preparation

on:
  pull_request:
    branches:
      - main
      - develop
      - release/*
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OWNER: $ {{ github.repository_owner }}
      DEST_BRANCH: ${{ github.base_ref }}
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Change targetRevision
      uses: ./
      with:
        name: 'application.yaml'
        owner: ${{ env.OWNER }}
        DestRevision: ${{ env.DEST_BRANCH }}